[project]
name = "edinet-doc-ingestion"
version = "0.1.0"
description = "Edinet Document Ingestion Lambda function"
requires-python = ">=3.13"
dependencies = ["requests>=2.32.0"]

[tool.uv]
dev-dependencies = ["ruff>=0.8.0"]
