networks:
  fino-network:
    driver: bridge

services:
  bespin:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - ${BESPIN_PORT}:3000
    volumes:
      - type: bind
        source: ./service/bespin/.mount
        target: /var/lib/grafana
      - type: bind
        source: ./service/bespin/grafana.ini
        target: /etc/grafana/grafana.ini
      - type: bind
        source: ./service/bespin/provisioning
        target: /etc/grafana/provisioning
    networks:
      - fino-network
    environment:
    # GRAFANA MUTABLE CONFIG VARIABLES
    # Production setting must use those variables as a secret like ** Docker secrets **
      - GF_SECURITY_ADMIN_PASSWORD=${BESPIN_ADMIN_PASSWORD}
      - GF_SECURITY_ADMIN_USER=${BESPIN_ADMIN_USER}
      - GF_INSTALL_PLUGINS=grafana-athena-datasource
