[project]
name = "fino"
version = "0.1.0"
description = "Fino - financial data platform -"
readme = "README.md"
requires-python = "==3.13.*"
dependencies = []

[dependency-groups]
dev = ["ruff>=0.14.8", "ruff-lsp>=0.0.1"]

[tool.uv.workspace]
members = ["cli", "src.kamino"]


[tool.ruff]
line-length = 80
