[project]
name = "edinet-doc-ingestion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "boto3>=1.41.2",
    "aws-lambda-powertools>=3.23.0",
]

[dependency-groups]
dev = []
